### ISSUE TITLE
remove unused `ReferenceStatistics` constructor

### ISSUE THREAD

**Issue by haakon-e** [CliMA/CalibrateEDMF.jl#291]
I think [this](https://github.com/CliMA/CalibrateEDMF.jl/blob/548ec9b5a1b0adea1af059d4a6b324346a78deab/src/ReferenceStats.jl#L134) constructor is not used. To be removed?

**Comment by haakon-e** [comment]
cc @yairchn @ilopezgp

**Comment by ilopezgp** [comment]
I guess you can try removing it and seeing what happens? We have coverage for all the constructors we actually use.
