### ISSUE TITLE
TurbulenceConvectionUtils test crashing but not reporting

### ISSUE THREAD

**Issue by haakon-e** [CliMA/CalibrateEDMF.jl#295]
There seems to be a test crashing in `TurbulenceConvectionUtils` (see e.g. [latest buildkite](https://buildkite.com/clima/calibrateedmf-ci/builds/1132#32d83534-bc1e-40fb-85bc-520e23b54f56)):
```
$ trap 'kill -- $' INT TERM QUIT; julia --color=yes --project test/TurbulenceConvectionUtils/runtests.jl
--
  | ┌ Error: TurbulenceConvection simulation crashed. DomainError(-1.6670134302907917, "Exponentiation yielding a complex result requires a complex argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")
  | └ @ CalibrateEDMF.TurbulenceConvectionUtils /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/depot/cpu/packages/TurbulenceConvection/tH8Rx/driver/main.jl:355
  | ┌ Warning: Note: t_end < ti, which means that simulation stopped before reaching the requested t_start.Requested t_start = 3600.0 s. However, the last time available is 800.0 s.Defaulting to penalized profiles...
  | └ @ CalibrateEDMF.ReferenceStats /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/1132/calibrateedmf-ci/src/ReferenceStats.jl:273
  | ┌ Error: TurbulenceConvection simulation crashed. DomainError(-1.667011933146744, "Exponentiation yielding a complex result requires a complex argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")
  | └ @ CalibrateEDMF.TurbulenceConvectionUtils /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/depot/cpu/packages/TurbulenceConvection/tH8Rx/driver/main.jl:355
  | ┌ Warning: TurbulenceConvection.jl simulation /tmp/jl_RmZzcU failed with parameters:
  | │ entrainment_factor = 0.15
  | │ dt_max = 210.0
  | │ τ_acnv_rai = 2500.0
  | └ @ CalibrateEDMF.TurbulenceConvectionUtils /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/1132/calibrateedmf-ci/src/TurbulenceConvectionUtils.jl:403
  | ┌ Error: TurbulenceConvection simulation crashed. DomainError(-1.6670031126569615, "Exponentiation yielding a complex result requires a complex argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")
  | └ @ CalibrateEDMF.TurbulenceConvectionUtils /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/depot/cpu/packages/TurbulenceConvection/tH8Rx/driver/main.jl:355
  | ┌ Error: TurbulenceConvection simulation crashed. DomainError(-1.6669992601063999, "Exponentiation yielding a complex result requires a complex argument.\nReplace x^y with (x+0im)^y, Complex(x)^y, or similar.")
  | └ @ CalibrateEDMF.TurbulenceConvectionUtils /central/scratch/esm/slurm-buildkite/calibrateedmf-ci/depot/cpu/packages/TurbulenceConvection/tH8Rx/driver/main.jl:355
  | Test Summary:             \| Pass  Total
  | TurbulenceConvectionUtils \|  116    116
```

I (think) I am unable to build a system image due to this.

cc @ilopezgp

**Comment by ilopezgp** [comment]
`| Test Summary:             \| Pass  Total
  | TurbulenceConvectionUtils \|  116    116`

That solves it, right? :)

**Comment by trontrytel** [comment]
Unless the expected outcome is a failure?

**Comment by haakon-e** [comment]
If I recall correctly, this
https://github.com/CliMA/CalibrateEDMF.jl/blob/9da299af7f60b124b823f7d9c82cdbd706eed18e/test/TurbulenceConvectionUtils/runtests.jl#L51-L55
is the line that causes breaking. As you can see, the test checks for `warnings` not failures.

**Comment by ilopezgp** [comment]
There are warnings in CalibrateEDMF, wrapping the error message from TC.jl. From your print

```
  | ┌ Warning: TurbulenceConvection.jl simulation /tmp/jl_RmZzcU failed with parameters:
  | │ entrainment_factor = 0.15
  | │ dt_max = 210.0
  | │ τ_acnv_rai = 2500.0
```

The time step is of course leading to failure, I specifically used two order of magnitudes larger of what is acceptable for that reason. The test_throws mode is `match_mode = :any `, which means I can just catch one of the prints. Otherwise, you could do @test_logs (:warn, :error). You can read the docs of the test suite for a more comprehensive view of this.

**Comment by haakon-e** [comment]
I see. That makes more sense. I don't know exactly how -- but I feel like it would be useful to indicate this in some way to future developers. It's a rather confusing discovery at first.

**Comment by ilopezgp** [comment]
> I see. That makes more sense. I don't know exactly how -- but I feel like it would be useful to indicate this in some way to future developers. It's a rather confusing discovery at first.

I agree. It would be nice if the @test_throw statement had functionality to silence _caught_ statements. Although they are printed beforehand, so I am not sure whether that is possible.

**Comment by ilopezgp** [comment]
You can change the test to `@test_logs(:warn, :error)` if you think that would be more clear!
