### ISSUE TITLE
improve error message in `get_stats_path`

### ISSUE THREAD

**Issue by haakon-e** [CliMA/CalibrateEDMF.jl#311]
Currently, if `get_stats_path(dir)` refers to a path that does have a `stats` folder, the method looks in `dir`. If no `.nc` file is found there, the following error message is returned:
```AssertionError: 0 stats files found with paths String[]```
This is rather unhelpful, primarily because the relevant code (L243):
https://github.com/CliMA/CalibrateEDMF.jl/blob/48d88fcb498e1ef7267eab1132c401e2380337fd/src/HelperFuncs.jl#L240-L250

prints the variable `stats_files` (i.e. after the glob search) instead of the variable `dir`. Needs to be fixed.

**Comment by charleskawczynski** [comment]
I think it’d be better to just close #230. All of the logic in that function can be removed if we prescribe the file names exactly, rather than finding the file. Also, the error will be super clear: file or path does not exist.
