### ISSUE TITLE
In `ReferenceModel`, allow for different `t_start` and `t_end` be used for les (mean and covar) and scm data

### ISSUE THREAD

**Issue by haakon-e** [CliMA/CalibrateEDMF.jl#32]
Currently it is assumed that the same time average interval is used to generate mean vector, covariance matrix, and forward model data.

Separate these quantities for mean, covariance and scm data.

Depends on #31.

**Comment by ilopezgp** [comment]
I get why you want to have a different averaging window for the covariance computation. But shouldn't the time window be the same for the mean observation and the mean of the scm data?

**Comment by haakon-e** [comment]
Yeah, I agree. Let's keep those windows the same. The primary use case was the covariance computation window.

**Comment by ilopezgp** [comment]
Discussed and fixed.
