### ISSUE TITLE
Variable name consistency

### ISSUE THREAD

**Issue by costachris** [CliMA/CalibrateEDMF.jl#49]
The current solution for mapping SCM->LES variable names is `get_les_names`:
https://github.com/CliMA/CalibrateEDMF.jl/blob/ac5704dcb695f1afe7d0cbbeb6997c6c99f7f6fa/src/helper_funcs.jl#L270
which maps to LES names on a case-by-case basis. The variable mapping seem slightly different than what's done for the MSE tables in `TC.jl`. For instance, `CEDMF` maps `"u_mean"-> "u_translational_mean"`, whereas the mse tables in TC.jl use `u_mean` for both SCM & LES.  Both `u_translational_mean` and `u_mean` are available in the LES stats files (and similarly for v). 

We may want to consider using a solution like [`TC.get_nc_data`,](https://github.com/CliMA/TurbulenceConvection.jl/blob/ed116efd9ef82dd4c0e280e3f67ec42ee73317dd/src/name_aliases.jl#L31) which is agnostic to whether a SCM or LES variable name is used when opening a netcdf. We could also replace `CEDMF.nc_fetch` entirely with `TC.get_nc_data`, but not sure how much we want to depend on TC source code. Note the name aliases in TC.jl don't map `u_mean`<=>`u_translational_mean` as in CEDMF

**Comment by ilopezgp** [comment]
Fixed.
