### ISSUE TITLE
get SCM vertical levels from namelist file instead of `.nc` simulation file.

### ISSUE THREAD

**Issue by haakon-e** [CliMA/CalibrateEDMF.jl#69]

**Comment by haakon-e** [comment]
**Two approaches:**
1. For non-isotropic domains, a TC namelist file will still define parameters for some function that generates vertical levels. Instead of running a simulation, we can generate these vertical levels using TC functions along with parameters from a namelist file
2. Run a simulation for 1 timestep (linked to #71), then fetch vertical levels with existing methods.

**Comment by ilopezgp** [comment]
We need to:

- Read z_scm (grid),
- Namelist (to modify parameters and generate runs),
- Location of TC.jl variables (z_c or z_f) without running a full simulation.

@charleskawczynski had some ideas of how this might be done without even running the simulation for a single time step.

**Comment by charleskawczynski** [comment]
Can call stuff defined in TC.jl's `integration_test/` folder?

**Comment by ilopezgp** [comment]
Fixed in #87 .
